export const USSD_MENU_TITLES = {
  main: {
    en: 'AEGIS GBV Support\n1. Report Incident\n2. Get Help\n3. Case Status\n4. Emergency Alert\n0. Exit',
    zu: 'Isisebenzi se-AEGIS\n1. Bhala Icala\n2. Thola Usizo\n3. Isimo Secala\n4. Isilindo Lokubhubhiseka\n0. Phuma',
    xh: 'Uncedo lwe-AEGIS\n1. Xela Isimangaliso\n2. Fumana Incedo\n3. Imisebenzi Yecala\n4. Ibhaleyilo Yethutyana\n0. Suka',
    st: 'Thuso ya AEGIS\n1. Gaka Ntswakiso\n2. Fumana Thuso\n3. Boemo ba Kgetsi\n4. Ikonokelo ya Ligokotsi\n0. Ema',
    af: 'AEGIS Ondersteuning\n1. Rapporteer Voorval\n2. Kry Hulp\n3. Saakstatus\n4. Noodtoestand\n0. Uitgang',
    ss: 'Incamo ye-AEGIS\n1. Phakamisa Icala\n2. Thola Usizo\n3. Isimo Secala\n4. I-Emergency Alert\n0. Phuma',
    tn: 'Thuso ya AEGIS\n1. Bega Kgetsi\n2. Kopa Thuso\n3. Boemo jwa Kgetsi\n4. Tlhagiso ya Tshoganetso\n0. Tswa',
    ts: 'Mpfuno wa AEGIS\n1. Vika Mhaka\n2. Kombela Mpfuno\n3. Xiyimo xa Mhaka\n4. Xivikelo xa xihatla\n0. Huma',
    ve: 'Thuso ya AEGIS\n1. Vhiga Mufhululu\n2. Humbela Thuso\n3. Tshiimo tsha Mufhululu\n4. Tsevho ya Tshihafu\n0. Bvuma',
    nso: 'Thuso ya AEGIS\n1. Bega Mohlala\n2. Kgopela Thuso\n3. Boemo bja Mohlala\n4. Temošo ya Tšhoganetšo\n0. Etswa',
    nr: 'Isizo le-AEGIS\n1. Bika Icala\n2. Funa Isizo\n3. Ubujamo Becala\n4. Isiyeleliso Esiphuthumako\n0. Phuma',
  },
  report_details: {
    en: 'Describe incident:\nBrief details please.',
    zu: 'Chaza lento okwenzeka:\nUmuntu muncinane.',
    xh: 'Chaza into eyenzeke:\nImininingwane emfutshane.',
    st: 'Thagela mokgatlho:\nThagela bonnyane.',
    af: 'Beskryf voorval:\nKorte besonderhede asseblief.',
    ss: 'Hlathula lokwakwenzela:\nUmuntu muncinane.',
    tn: 'Tlhalosa tiragalo:\nDintlha tse dikhutshwane tsweetswee.',
    ts: 'Hlamusela mhaka:\nVuxokoxoko byo koma ndza kombela.',
    ve: 'Talutshedzani mufhululu:\nZwidodombedzwa zwi pfufhi nga khumbelo.',
    nso: 'Hlalosa tiragalo:\nDintlha tše dikopana hle.',
    nr: 'Hlathulula isehlakalo:\nImininingwana emifitjhani ngiyabawa.',
  },
  help_details: {
    en: 'What help do you need?\n1. Shelter\n2. Counseling\n3. Medical\n4. Police',
    zu: 'Yini usizo okudingayo?\n1. Ikhaya\n2. Ukunandisana\n3. Iziguli\n4. Amapolisa',
    xh: 'Yoluphi uncedo onodinga?\n1. Indawo Yokuhlala\n2. Untetho\n3. Izigqebela\n4. Amapolisa',
    st: 'Thuso efe o nago go e fumana?\n1. Mophato\n2. Kgetsi\n3. Bolwetse\n4. Mapodisi',
    af: 'Watter hulp het u nodig?\n1. Skuiling\n2. Terapie\n3. Mediese\n4. Polisie',
    ss: 'Yini usizo okudingayo?\n1. Ikhaya\n2. Ukunandisana\n3. Iziguli\n4. Amapolisa',
    tn: 'O tlhoka thuso efe?\n1. Lefelo la go iphitlha\n2. Bogakolodi\n3. Kalafi\n4. Mapodisi',
    ts: 'U lava mpfuno wihi?\n1. Ndhawu yo tumbela\n2. Ntsundzuxo\n3. Vutshunguri\n4. Maphorisa',
    ve: 'Ni khou toda thuso ifhio?\n1. Fhethu ha u dzumbama\n2. Vhueletshedzi\n3. Tshihedzwa\n4. Mapholisa',
    nso: 'O hloka thuso efe?\n1. Lefelo la go iphihla\n2. Keletšo\n3. Kalafo\n4. Maphodisa',
    nr: 'Udinga isizo elinjani?\n1. Indawo yokuphephela\n2. Ukwelulekwa\n3. Ezamapilo\n4. Amapholisa',
  },
  case_reference: {
    en: 'Enter case ID or number:',
    zu: 'Faka isithombelo secala noma inombolo:',
    xh: 'Faka ikhowudi yecala okanye inombolo:',
    st: 'Kenya khowudi ya kgetsi kgonwa le nomoro:',
    af: 'Voer saak-ID of nommer in:',
    ss: 'Faka isithombelo secala noma inombolo:',
    tn: 'Tsenya ID kgotsa nomoro ya kgetsi:',
    ts: 'Nghenisa ID kumbe nomboro ya mhaka:',
    ve: 'Dzhenisani ID kana nomboro ya mufhululu:',
    nso: 'Tsenya ID goba nomoro ya mohlala:',
    nr: 'Faka i-ID namkha inomboro yecala:',
  },
  emergency_alert: {
    en: 'Emergency - Police being notified. Stay safe.',
    zu: 'Ibhaleyilo - Amapolisa azotiwe. Hlala naphakeme.',
    xh: 'I-emergency - Amapolisa azonicelwa. Hlala ekhuselekile.',
    st: 'Kotsi - Mapodisi a tla lemoga. Dula a sa lwala.',
    af: 'Noodtoestand - Polisie word in kennis gestel. Bly veilig.',
    ss: 'I-Emergency - Amapolisa azonicelwa. Hlala ekhuselekile.',
    tn: 'Tshoganetso - Mapodisi a a itsisetswe. Nna o sireletsegile.',
    ts: 'Xihatla - Maphorisa ya tivisiwile. Tshama u sirhelelekile.',
    ve: 'Tshihafu - Mapholisa vha khou divhadzwa. Dzudzani no tsireledzea.',
    nso: 'Tšhoganetšo - Maphodisa a tsebišitšwe. Dula o bolokegile.',
    nr: 'Isiphuthumako - Amapholisa ayabikelwa. Hlala uphephile.',
  },
  end: {
    en: '0. Back to Menu\n*. Exit',
    zu: '0. Buya Ekumenyu\n*. Phuma',
    xh: '0. Buya Kwemenu\n*. Suka',
    st: '0. Koma go Menya\n*. Ema',
    af: '0. Terug na Keuzemenu\n*. Uitgang',
    ss: '0. Buya Ekumenyu\n*. Phuma',
    tn: '0. Boela kwa Menung\n*. Tswa',
    ts: '0. Tlhela eka Menu\n*. Huma',
    ve: '0. Vhuyelela kha Menu\n*. Bvuma',
    nso: '0. Boela go Menu\n*. Etswa',
    nr: '0. Buyela kuMenyu\n*. Phuma',
  },
} as const;

export const USSD_MENU_STRUCTURE = {
  main: [
    { key: '1', label: 'Report Incident', nextMenu: 'report_details', action: 'report', requiresInput: true },
    { key: '2', label: 'Get Help', nextMenu: 'help_details', action: 'help', requiresInput: true },
    { key: '3', label: 'Case Status', nextMenu: 'case_reference', action: 'status', requiresInput: true },
    { key: '4', label: 'Emergency Alert', nextMenu: 'emergency_alert', action: 'emergency' },
  ],
  report_details: [],
  help_details: [],
  case_reference: [],
  emergency_alert: [],
  confirmation: [],
  help_confirmation: [],
  case_not_found: [],
  case_status_result: [],
  error: [],
  end: [],
} as const;
